### ISSUE TITLE
Quan el nom de l'expedient conté caracters no suportats perl sistema de fitxers

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/gdib#16]
Vaig intentar crear un expedient amb nom "209361_05/08/2019 12:15:03" i em donava l'error de més abaix. Al final va resultar que l'Alfresco no suporta certs caràcters, concretament els no suportats normalment pel sistma de fitxers "\ / : * ? " < > |"

Arreglar-ho per a que amolli un error més descriptiu i no es quedi 1 minuts esperant i després llanci l'error del final.

`Caused` by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object,
 'true', 'false' or 'null')
 at [Source: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/esb/services/createFile">POST&nbsp;/esb/services/createFile</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>
; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1624)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
        at es.caib.arxiudigital.apirest.utils.UtilJSON.ConvertirAClaseJava(UtilJSON.java:65)
        at es.caib.arxiudigital.apirest.ApiArchivoDigital.obtenerResultadoExcepcionJSON(ApiArchivoDigital.java:2672)
        at es.caib.arxiudigital.apirest.ApiArchivoDigital.crearExpediente(ApiArchivoDigital.java:1527)
        at org.fundaciobit.plugins.documentcustody.arxiudigitalcaib.ArxiuDigitalCAIBDocumentCustodyPlugin.reserveCustodyID(ArxiuDigitalCAIBDocumentCus
todyPlugin.java:518)`

**Comment by atrobat-dgtic** [comment]
Aquest issue ja està arreglat. He pogut crear un expedient amb nom 209361_05/08/2019 12:15:03
