### ISSUE TITLE
Error recurrente en la validación de documentos

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/gdib#26]
Recurrentemente en los logs aparecen errores del siguiente tipo. Parece que no impiden el funcionamiento de las operaciones de archivo però deberían eliminarse.

2018-01-30 10:48:12,232 ERROR [es.gob.afirma.utils.UtilsSignature] La firma proporcionada no posee una estructura XML vÃ¯ ¿ ½a.dd
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
at es.gob.afirma.utils.UtilsSignature.getDocumentFromXML(UtilsSignature.java:1874)
at es.gob.afirma.signature.SignatureFormatDetector.isXMLFormat(SignatureFormatDetector.java:273)
at es.gob.afirma.integraFacade.GenerateMessageRequest.incorporateSignatureImplicit(GenerateMessageRequest.java:641)
at

(Tarea importada desde Redmine)

**Comment by tgaya-dgtic** [comment]
Este es un error sin solución en la versión actual de @firma.
Pendiente de cerrar incidencia.
